# Generated by Django 5.0.7 on 2024-07-31 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('periodicity', models.SmallIntegerField(verbose_name='Периодичность')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('pleasant_habit', models.BooleanField(default=False, verbose_name='Полезная привычка')),
                ('related_habit', models.BooleanField(null=True, verbose_name='Приятная привычка')),
                ('reward', models.CharField(null=True, verbose_name='Вознаграждение')),
                ('is_public', models.BooleanField(verbose_name='Видно всем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
