# Generated by Django 5.0.7 on 2024-08-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='related_habit',
        ),
    ]
