# Generated by Django 5.0.7 on 2024-08-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_related_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Время на выполнение'),
        ),
    ]
