# Generated by Django 5.0.7 on 2024-08-02 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_habit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
